config/routes.rb
Rails.application.routes.draw do

  get "/sitemaps/sitemap.xml" => "sitemaps#sitemap", format: :xml, as: :sitemap

  scope :module => 'buttercms' do
    post '/subscribe_user' => 'base#subscribe_user'

    post '/tags/:slug/posts' => 'tags#fetch_posts'
    get '/tags/:slug' => 'tags#show', :as => :buttercms_tag

    post '/posts/list' => 'posts#fetch_posts'
    get '/posts/all' => 'posts#all_posts'
    get '/posts/search' => 'posts#search_post'
    post '/posts/search' => 'posts#search'

    post '/categories/:slug/posts' => 'categories#fetch_posts'
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category

    post '/authors/:slug/posts' => 'authors#fetch_posts'
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    # get '/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap


    # Redirects
    get '/2017/09/04/august-highlights.html', to: redirect('/august-highlights')
    get '/2017/09/01/travelex-improved-continuous-integration-with-bitrise.html', to: redirect('/travelex-improved-continuous-integration-with-bitrise')
    get '/2017/08/31/we-support-xcode-9-s-new-exportoptions-property.html', to: redirect('/we-support-xcode-9-s-new-exportoptions-property')
    get '/2017/08/25/set-your-build-version-on-bitrise-automatically.html', to: redirect('/set-your-build-version-on-bitrise-automatically')
    get '/2017/08/23/install-missing-android-sdk-components-step-for-react-native.html', to: redirect('/install-missing-android-sdk-components-step-for-react-native')
    get '/2017/08/22/registering-new-ios-devices.html', to: redirect('/registering-ios-devices')
    get '/2017/08/18/slack-away.html', to: redirect('/slack-away')
    get '/2017/08/16/one-ios-app-multiple-configurations.html', to: redirect('/one-ios-app-multiple-configurations')
    get '/2017/08/15/new-export-options-plist-in-Xcode-9.html', to: redirect('/new-export-options-plist-in-xcode-9')
    get '/2017/08/11/build-different-release-signed-ipas-for-your-xamarin-ios-project.html', to: redirect('/build-different-release-signed-ipas-for-your-xamarinios-project')
    get '/2017/08/10/unity-for-the-win-on-bitrise-too.html', to: redirect('/unity-for-the-win-on-bitrise-too')
    get '/2017/08/07/droids-on-roids-how-to-connect-physical-devices-to-bitrise-io.html', to: redirect('/droids-on-roids-how-to-connect-physical-devices-to-bitriseio')
    get '/2017/08/04/4-things-to-remember-when-upgrading-a-production-virtual-machine.html', to: redirect('/4-things-to-remember-when-upgrading-a-production-virtual-machine')
    get '/2017/08/02/july-highlights.html', to: redirect('/july-highlights')
    get '/2017/08/01/bitrise-raises-3-2-million-in-series-a-funding.html', to: redirect('/bitrise-raises-3-2-million-in-series-a-funding')
    get '/2017/07/28/danger-danger-uh-that-is-using-danger-with-bitrise.html', to: redirect('/danger-danger-uh-that-is-using-danger-with-bitrise')
    get '/2017/07/27/introducing-full-cross-platform-support.html', to: redirect('/introducing-full-cross-platform-support')
    get '/2017/07/25/how-to-set-up-a-react-native-app-on-bitrise.html', to: redirect('/how-to-set-up-a-react-native-app-on-bitrise')
    get '/2017/07/20/ifttt-bitrise-magic.html', to: redirect('/lets-automate-together-bitrise-ifttt')
    get '/2017/07/17/yoyo-wallet-shipping-fast-and-frequently-with-bitrise.html', to: redirect('/yoyo-wallet-shipping-fast-and-frequently-with-bitrise')
    get '/2017/07/14/extra-minutes-on-hobby-plan.html', to: redirect('/extra-minutes-on-hobby-plan')
    get '/2017/01/27/state-of-app-development-in-2016.html', to: redirect('/state-of-app-development-2016')
    get '/2017/01/14/weekly-virtual-machine-stack-updates-now-on-discuss-bitrise-io.html', to: redirect('/weekly-vritual-machine-stack-updates-now-on-discuss')
    get '/2016/12/12/the-new-devcenter-finally-arrived.html', to: redirect('/the-new-devcenter-has-finally-arrived')
    get '/2016/10/31/xcode-8-1-final-on-macos-sierra.html', to: redirect('/xcode-8-1-final-on-macos-sierra')
    get '/2016/10/18/gifs-make-everything-better.html', to: redirect('/gifs-make-everything-better')
    get '/2016/10/15/trigger-builds-with-git-tags.html', to: redirect('/trigger-builds-with-git-tags')
    get '/2016/10/12/disable-and-trigger-scheduled-builds-on-demand.html', to: redirect('/disable-and-trigger-scheduled-builds-on-demand')
    get '/2016/10/06/bitbucket-pull-request-support-is-here.html', to: redirect('/bitbucket-pull-request-support-is-here')
    get '/2016/09/23/do-more-with-triggers.html', to: redirect('/do-more-with-triggers')
    get '/2016/09/21/xcode-8-and-automatic-code-signing.html', to: redirect('/xcode-8-and-automatic-code-signing')
    get '/2016/09/17/cocoapods-issue-and-fix-with-xcode-8.html', to: redirect('/cocoapods-issue-and-fix-with-xcode-8')
    get '/2016/09/06/new-tutorial-configuring-and-using-vpn.html', to: redirect('/new-tutorial-configuring-and-using-vpn')
    get '/2016/08/30/manage-your-dev-team-like-a-boss-through-the-all-new-organizations.html', to: redirect('/manage-your-dev-team-like-a-boss-through-the-all-new-organizations')
    get '/2016/08/25/new-team-handling-features.html', to: redirect('/new-team-handling-features')
    get '/2016/08/23/end-of-summer-tweaks.html', to: redirect('/end-of-summer-tweaks')
    get '/2016/08/19/android-could-not-find-appcompat-v7-how-to-update-preinstalled-packages.html', to: redirect('/android-could-not-find-appcompat-v7-how-to-update-preinstalled-packages')
    get '/2016/08/17/new-gradle-runner-version-gradlew-path-is-now-required.html', to: redirect('/new-gradle-runner-version-gradlew-path-is-now-required')
    get '/2016/06/23/slack-webhook-specify-custom-environment-variables.html', to: redirect('/trigger-a-build-from-slack-now-with-custom-environment-variables')
    get '/2016/06/07/automatic-ios-wildcard-development-code-signing-files.html', to: redirect('/automatic-ios-wildcard-development-code-signing-files')
    get '/2016/06/06/ios-code-signing-a-new-method.html', to: redirect('/ios-code-signing-a-new-method')
    get '/2016/05/13/pretty-little-updates.html', to: redirect('/pretty-little-updates')
    get '/2016/04/29/hooking-up-a-middleman-project-to-deploy-a-static-site-to-heroku-with-bitrise.html', to: redirect('/hooking-up-a-middleman-project-to-deploy-a-static-site-to-heroku-with-bitrise')
    get '/2016/03/22/xamarin-ci-with-bitrise-tutorial-part-3-deploy.html', to: redirect('/xamarin-ci-with-bitrise-tutorial-part-3-deploy')
    get '/2016/03/05/xamarin-ci-with-bitrise-tutorial-part-2-testing.html', to: redirect('/xamarin-ci-with-bitrise-tutorial-part-2-testing')
    get '/2016/02/29/xamarin-ci-with-bitrise-tutorial-part-1-getting-started.html', to: redirect('/xamarin-ci-with-bitrise-tutorial-part-1-getting-started')
    get '/2016/02/23/all-the-webhooks-you-need.html', to: redirect('/all-the-webhooks-you-need')
    get '/2016/02/12/edit-your-yaml-files-like-a-boss.html', to: redirect('/edit-your-yaml-files-like-a-boss')
    get '/2016/02/11/xamarin-users-rejoice.html', to: redirect('/xamarin-users-rejoice')
    get '/2016/02/08/a-better-pricing-for-you.html', to: redirect('/a-better-pricing-for-you')
    get '/2016/02/04/let-s-move-to-the-new-stack.html', to: redirect('/lets-move-to-the-new-stack')
    get '/2016/01/20/here-comes-the-new-stack.html', to: redirect('/here-comes-the-new-stack')
    get '/2016/01/11/the-new-year-together.html', to: redirect('/the-new-year-together')
    get '/2015/11/23/finally-build-your-android-projects-on-bitrise.html', to: redirect('/finally-build-your-android-projects-on-bitrise')
    get '/2015/11/05/schedule-those-builds.html', to: redirect('/build-notification-emails-are-cooler-than-ever')
    get '/2015/11/05/schedule-those-builds.html', to: redirect('/schedule-those-builds')
    get '/2015/10/28/updated-build-logs-with-new-shiny-practical-features.html', to: redirect('/updated-build-logs-with-shiny-practical-features')
    get '/2015/10/19/booyah-our-command-line-interface-just-got-its-own-landing-page.html', to: redirect('/booyah-our-command-line-interface-just-got-its-own-landing-page')
    get '/2015/08/05/introducing-fastlane-on-bitrise.html', to: redirect('/introducing-fastlane-on-bitrise')
    get '/2015/06/24/a-tech-startup-in-london.html', to: redirect('/a-tech-startup-in-london')
    get '/2015/04/29/you-can-now-transfer-the-ownership-of-your-apps.html', to: redirect('/you-can-now-transfer-the-ownership-of-your-apps')
    get '/2015/04/28/announcing-status-images.html', to: redirect('/announcing-status-images')
    get '/2015/04/23/pull-request-support-for-github-repositories.html', to: redirect('/pull-request-support-for-github-repositories')
    get '/2015/01/29/the-new-workflow-system.html', to: redirect('/the-new-workflow-system')
    get '/2014/11/24/we-re-back-from-how-to-web.html', to: redirect('/were-back-from-how-to-web')
    get '/2014/10/29/bitrise-is-one-of-this-year-s-startup-spotlight-finalists.html', to: redirect('/bitrise-is-one-of-this-years-how-to-web-startup-spotlight-finalists')
    get '/2014/07/14/renaming.html', to: redirect('/renaming')

    get '(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/:slug' => 'posts#show', :as => :buttercms_post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/buttercms/authors_controller.rb
class Buttercms::AuthorsController < Buttercms::BaseController
	before_action :set_variables

	def show
		@author = ButterCMS::Author.find(params[:slug])
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size,
			author_slug: params[:slug]
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end
private
	def set_variables
		@categories = ButterCMS::Category.all
	end
end

app/controllers/buttercms/base_controller.rb
class Buttercms::BaseController < ActionController::Base
	# You can of course change this layout to your main application layout
	# to have your blog match the rest of your site.
	layout 'buttercms/default'
	include Response
	include ExceptionHandler

	def subscribe_user
		respond_to do |format|
			if !subscribe_params[:email].eql?("")
				begin
					encoded_authorization_token = "Basic " + Base64.strict_encode64("slapec:#{ENV['MAILCHIMP_API_TOKEN']}")

					query = "query=" + subscribe_params[:email]
					response = RestClient::Request.execute(
						method: :get,
						url: "#{ENV['MAILCHIMP_API_SERVER']}/search-members?#{query}",
						headers: {
							"Authorization": encoded_authorization_token
						}
					)
					response_body = JSON.parse(response.body)
					if response_body["exact_matches"]["total_items"] > 0
						format.json{ render json: {message: "already subscribed"}.to_json(), status: :ok }
					end

					response = RestClient::Request.execute(
						method: :post,
						url: "#{ENV['MAILCHIMP_API_SERVER']}/lists/#{ENV['MAILCHIMP_LIST_ID']}/members",
						headers: {
							"Authorization": encoded_authorization_token,
							"Content-Type": "application/json"
						},
						payload: {
							email_address: subscribe_params[:email],
							status: "subscribed"
						}.to_json()
					)
					format.json{ render json: {message: "ok"}.to_json(), status: :ok }
				rescue RestClient::ExceptionWithResponse
					format.json{ render json: {message: "invalid email"}.to_json(), status: :internal_server }
				end
			else
				format.json{ render json: {message: "empty email"}.to_json(), status: :bad_request }
			end
		end
	end

private

	def subscribe_params
		params.require(:base).permit(:email)
	end
end

app/controllers/buttercms/categories_controller.rb
class Buttercms::CategoriesController < Buttercms::BaseController
	before_action :set_variables

	def show
		@category = ButterCMS::Category.find(params[:slug])
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size,
			category_slug: params[:slug]
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end
private
	def set_variables
		@categories = ButterCMS::Category.all
	end
end

app/controllers/buttercms/feeds_controller.rb
class Buttercms::FeedsController < Buttercms::BaseController
  def sitemap
    feed = ButterCMS::Feed.find(:sitemap)

    render :xml => feed.data
  end

  def atom
    feed = ButterCMS::Feed.find(:atom)

    render :xml => feed.data
  end

  def rss
    feed = ButterCMS::Feed.find(:rss)

    render :xml => feed.data
  end
end

app/controllers/buttercms/posts_controller.rb
class Buttercms::PostsController < Buttercms::BaseController
	before_action :set_variables

	def index
		tag = ButterCMS::Tag.find("featured", include: 'recent_posts')
		@featured_post = tag.data.recent_posts.first unless tag.nil?

		@posts = ButterCMS::Post.all(:page => params[:page], :page_size => 6, include: 'recent_posts')

		@next_page = @posts.meta.next_page
		@previous_page = @posts.meta.previous_page
	end

	def show
		@post = ButterCMS::Post.find(params[:slug])

		meta_description_elements = parse_meta_description(@post.meta_description)
		@meta_description = meta_description_elements[:meta_description].strip!
		@authors = get_authors([@post.author.slug] + meta_description_elements[:authors])
		@next_post = @post.meta.next_post
		@previous_post = @post.meta.previous_post
	end

	def all_posts
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end

	def search_post
		@search_query = params[:query]
		render :search
	end

	def search
		page = post_params[:page] || 1
		page_size = post_params[:page] ? 6 : 100

		@posts = ButterCMS::Post.search(post_params[:query], {page: page, page_size: page_size})
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end

		rescue => ex
			if ex.class == ButterCMS::NotFound
				json_response(ex, :not_found)
			else
				json_response(ex, :internal_server)
			end
	end

private
	def post_params
		params.require(:post).permit(:query, :page, :page_size)
	end

	def set_variables
		@categories = ButterCMS::Category.all
		@tags = ButterCMS::Tag.all
	end

	def parse_meta_description(description)
		elements = description.split("*")
		meta_description = elements.first
		authors = elements[1..elements.length]
		return {
			meta_description: meta_description,
			authors: authors
		}
	end

	def get_authors(author_slugs)
		authors = []
		author_slugs.each do |author_slug|
			begin
				authors << ButterCMS::Author.find(author_slug)
			rescue => ex
				puts "[!] Exception: Author not found by slug (#{author_slug})! Exception: #{ex}, #{ex.inspect}"
			end
		end
		return authors
	end
end

app/controllers/buttercms/tags_controller.rb
class Buttercms::TagsController < Buttercms::BaseController
	before_action :set_variables

	def show
		@tag = ButterCMS::Tag.find(params[:slug])
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size,
			tag_slug: params[:slug]
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end
private
	def set_variables
		@categories = ButterCMS::Category.all
	end
end

app/views/buttercms/base/_author.html.erb
<div class="author-info">
    <div class="author-container">
        <img alt="<%= author.first_name %> <%= author.last_name %> avatar" src="<%= author.profile_image.eql?("") ? image_path('blog_default_avatar') : author.profile_image %>">
        <div class="name-and-title">
            <%= link_to "#{author.first_name} #{author.last_name}", buttercms_author_path(author.slug) %>
            <% if !author.title.eql? "" %>
                <p><%= author.title %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/buttercms/base/_author_header.html.erb
<div class="author-header-container">
    <div class="all-articles">all articles by</div>
    <%= render partial: 'author', locals: {author: author} %>
</div>

app/views/buttercms/base/_authors.html.erb
<div class="author-info">
    <% authors.each do |author| %>
        <div class="author-container">
            <img src="<%= author.profile_image.eql?("") ? image_path('blog_default_avatar') : author.profile_image %>">
            <div class="name-and-title">
                <%= link_to "#{author.first_name} #{author.last_name}", buttercms_author_path(author.slug) %>
                <% if !author.title.eql? "" %>
                    <p><%= author.title %></p>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/buttercms/base/_categories.html.erb
<%= react_component('Categories', { categories: @categories.map{|c| {path: buttercms_category_path(c.slug), name: c.name.capitalize}} }) %>

app/views/buttercms/base/_footer.html.erb
<div class="footer">
  <div class="top-footer">
    <div class="socials">
      <h4>Always stay in the loop!</h4>
      <div class="separator"></div>
      <div class="social-icons">
        <a class="twitter" href="https://twitter.com/bitrise" tabindex="-1" target="_blank">
          <span><%= svg("social_icons/twitter_footer") %></span>
        </a>
        <a class="facebook" href="https://facebook.com/bitrise.io" tabindex="-1" target="_blank">
          <span><%= svg("social_icons/facebook_footer") %></span>
        </a>
        <a class="slack" href="https://chat.bitrise.io/" tabindex="-1" target="_blank">
          <span><%= svg("social_icons/slack") %></span>
        </a>
        <a class="github" href="https://github.com/bitrise-io" tabindex="-1" target="_blank">
          <span><%= svg("social_icons/github") %></span>
        </a>
      </div><a class="v3-button big status-page none" target="_blank" href="https://status.bitrise.io/">All Systems Operational</a>
    </div>
    <div class="product">
      <h4>Product</h4>
      <div class="separator"></div>
      <a tabindex="-1" href="https://www.bitrise.io/pricing?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Pricing</a>
      <a tabindex="-1" href="https://www.bitrise.io/cli?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">CLI</a>
      <a tabindex="-1" href="https://www.bitrise.io/integrations?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Integrations</a>
    </div>
    <div class="company">
      <h4>Company</h4>
      <div class="separator"></div>
      <a tabindex="-1" href="https://www.bitrise.io/about?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">About</a>
      <a tabindex="-1" href="https://bitrise.io/jobs?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Careers</a>
      <a tabindex="-1" href="https://www.bitrise.io/terms?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Terms</a>
      <a tabindex="-1" href="https://www.bitrise.io/privacy?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Privacy policy</a>
      <a tabindex="-1" href="https://www.bitrise.io/cookie_policy?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Cookie policy</a>
    </div>
    <div class="support">
      <h4>Support</h4>
      <div class="separator"></div>
      <a target="_blank" tabindex="-1" href="https://devcenter.bitrise.io">Docs &amp; DevCenter</a>
      <a target="_blank" tabindex="-1" href="https://discuss.bitrise.io">Discuss</a>
      <a target="_blank" tabindex="-1" href="https://blog.bitrise.io/">News Blog</a>
      <a tabindex="-1" href="https://www.bitrise.io/contact?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Contact</a>
    </div>
  </div>
  <div class="bottom-footer">
    <h4>Compiled with <span class="heart-container"><%= svg("footer_heart") %></span>in London &amp; Budapest</h4>
    <a class="copyright" target="_blank" tabindex="-1" href="https://www.bitrise.io?utm_source=bitriseblog&utm_medium=web&utm_campaign=static">Copyright © 2014-<%= Time.zone.now.year %> Bitrise ltd.</a>
  </div>
</div>

app/views/buttercms/base/_hero.html.erb
<div class="hero">
  <div class="content-wrapper">
    <div class="hero-inner">
      <div class="newsletter">
        <h1>Bitrise Blog</h1>
        <div class="text">
          <p>Articles about Continuous Integration & Delivery, automation, iOS code signing, DevOps, and awesome tech</p>
          <%= react_component('Subscription') %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buttercms/base/_navigation.html.erb
<%= react_component('Menu') %>

app/views/buttercms/base/_try_bitrise.html.erb
<div class="try-wrapper">
    <div class="container">
        <h2>Try Bitrise</h2>
        <h1>Automate your building, testing and deployment</h1>
        <a href="https://www.bitrise.io/users/sign_up?utm_source=bitriseblog&utm_medium=web&utm_campaign=static" class="start-building-button">Start building for free</a>
    </div>
</div>