config/routes.rb
Rails.application.routes.draw do

  get "/sitemaps/sitemap.xml" => "sitemaps#sitemap", format: :xml, as: :sitemap

  scope :module => 'buttercms' do
    post '/subscribe_user' => 'base#subscribe_user'

    post '/tags/:slug/posts' => 'tags#fetch_posts'
    get '/tags/:slug' => 'tags#show', :as => :buttercms_tag

    post '/posts/list' => 'posts#fetch_posts'
    get '/posts/all' => 'posts#all_posts'
    get '/posts/search' => 'posts#search_post'
    post '/posts/search' => 'posts#search'

    post '/categories/:slug/posts' => 'categories#fetch_posts'
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category

    post '/authors/:slug/posts' => 'authors#fetch_posts'
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    # get '/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap


    # Redirects
    get '/2017/09/04/august-highlights.html', to: redirect('/august-highlights')
    get '/2017/09/01/travelex-improved-continuous-integration-with-bitrise.html', to: redirect('/travelex-improved-continuous-integration-with-bitrise')
    get '/2017/08/31/we-support-xcode-9-s-new-exportoptions-property.html', to: redirect('/we-support-xcode-9-s-new-exportoptions-property')
    get '/2017/08/25/set-your-build-version-on-bitrise-automatically.html', to: redirect('/set-your-build-version-on-bitrise-automatically')
    get '/2017/08/23/install-missing-android-sdk-components-step-for-react-native.html', to: redirect('/install-missing-android-sdk-components-step-for-react-native')
    get '/2017/08/22/registering-new-ios-devices.html', to: redirect('/registering-ios-devices')
    get '/2017/08/18/slack-away.html', to: redirect('/slack-away')
    get '/2017/08/16/one-ios-app-multiple-configurations.html', to: redirect('/one-ios-app-multiple-configurations')
    get '/2017/08/15/new-export-options-plist-in-Xcode-9.html', to: redirect('/new-export-options-plist-in-xcode-9')
    get '/2017/08/11/build-different-release-signed-ipas-for-your-xamarin-ios-project.html', to: redirect('/build-different-release-signed-ipas-for-your-xamarinios-project')
    get '/2017/08/10/unity-for-the-win-on-bitrise-too.html', to: redirect('/unity-for-the-win-on-bitrise-too')
    get '/2017/08/07/droids-on-roids-how-to-connect-physical-devices-to-bitrise-io.html', to: redirect('/droids-on-roids-how-to-connect-physical-devices-to-bitriseio')
    get '/2017/08/04/4-things-to-remember-when-upgrading-a-production-virtual-machine.html', to: redirect('/4-things-to-remember-when-upgrading-a-production-virtual-machine')
    get '/2017/08/02/july-highlights.html', to: redirect('/july-highlights')
    get '/2017/08/01/bitrise-raises-3-2-million-in-series-a-funding.html', to: redirect('/bitrise-raises-3-2-million-in-series-a-funding')
    get '/2017/07/28/danger-danger-uh-that-is-using-danger-with-bitrise.html', to: redirect('/danger-danger-uh-that-is-using-danger-with-bitrise')
    get '/2017/07/27/introducing-full-cross-platform-support.html', to: redirect('/introducing-full-cross-platform-support')
    get '/2017/07/25/how-to-set-up-a-react-native-app-on-bitrise.html', to: redirect('/how-to-set-up-a-react-native-app-on-bitrise')
    get '/2017/07/20/ifttt-bitrise-magic.html', to: redirect('/lets-automate-together-bitrise-ifttt')
    get '/2017/07/17/yoyo-wallet-shipping-fast-and-frequently-with-bitrise.html', to: redirect('/yoyo-wallet-shipping-fast-and-frequently-with-bitrise')
    get '/2017/07/14/extra-minutes-on-hobby-plan.html', to: redirect('/extra-minutes-on-hobby-plan')
    get '/2017/01/27/state-of-app-development-in-2016.html', to: redirect('/state-of-app-development-2016')
    get '/2017/01/14/weekly-virtual-machine-stack-updates-now-on-discuss-bitrise-io.html', to: redirect('/weekly-vritual-machine-stack-updates-now-on-discuss')
    get '/2016/12/12/the-new-devcenter-finally-arrived.html', to: redirect('/the-new-devcenter-has-finally-arrived')
    get '/2016/10/31/xcode-8-1-final-on-macos-sierra.html', to: redirect('/xcode-8-1-final-on-macos-sierra')
    get '/2016/10/18/gifs-make-everything-better.html', to: redirect('/gifs-make-everything-better')
    get '/2016/10/15/trigger-builds-with-git-tags.html', to: redirect('/trigger-builds-with-git-tags')
    get '/2016/10/12/disable-and-trigger-scheduled-builds-on-demand.html', to: redirect('/disable-and-trigger-scheduled-builds-on-demand')
    get '/2016/10/06/bitbucket-pull-request-support-is-here.html', to: redirect('/bitbucket-pull-request-support-is-here')
    get '/2016/09/23/do-more-with-triggers.html', to: redirect('/do-more-with-triggers')
    get '/2016/09/21/xcode-8-and-automatic-code-signing.html', to: redirect('/xcode-8-and-automatic-code-signing')
    get '/2016/09/17/cocoapods-issue-and-fix-with-xcode-8.html', to: redirect('/cocoapods-issue-and-fix-with-xcode-8')
    get '/2016/09/06/new-tutorial-configuring-and-using-vpn.html', to: redirect('/new-tutorial-configuring-and-using-vpn')
    get '/2016/08/30/manage-your-dev-team-like-a-boss-through-the-all-new-organizations.html', to: redirect('/manage-your-dev-team-like-a-boss-through-the-all-new-organizations')
    get '/2016/08/25/new-team-handling-features.html', to: redirect('/new-team-handling-features')
    get '/2016/08/23/end-of-summer-tweaks.html', to: redirect('/end-of-summer-tweaks')
    get '/2016/08/19/android-could-not-find-appcompat-v7-how-to-update-preinstalled-packages.html', to: redirect('/android-could-not-find-appcompat-v7-how-to-update-preinstalled-packages')
    get '/2016/08/17/new-gradle-runner-version-gradlew-path-is-now-required.html', to: redirect('/new-gradle-runner-version-gradlew-path-is-now-required')
    get '/2016/06/23/slack-webhook-specify-custom-environment-variables.html', to: redirect('/trigger-a-build-from-slack-now-with-custom-environment-variables')
    get '/2016/06/07/automatic-ios-wildcard-development-code-signing-files.html', to: redirect('/automatic-ios-wildcard-development-code-signing-files')
    get '/2016/06/06/ios-code-signing-a-new-method.html', to: redirect('/ios-code-signing-a-new-method')
    get '/2016/05/13/pretty-little-updates.html', to: redirect('/pretty-little-updates')
    get '/2016/04/29/hooking-up-a-middleman-project-to-deploy-a-static-site-to-heroku-with-bitrise.html', to: redirect('/hooking-up-a-middleman-project-to-deploy-a-static-site-to-heroku-with-bitrise')
    get '/2016/03/22/xamarin-ci-with-bitrise-tutorial-part-3-deploy.html', to: redirect('/xamarin-ci-with-bitrise-tutorial-part-3-deploy')
    get '/2016/03/05/xamarin-ci-with-bitrise-tutorial-part-2-testing.html', to: redirect('/xamarin-ci-with-bitrise-tutorial-part-2-testing')
    get '/2016/02/29/xamarin-ci-with-bitrise-tutorial-part-1-getting-started.html', to: redirect('/xamarin-ci-with-bitrise-tutorial-part-1-getting-started')
    get '/2016/02/23/all-the-webhooks-you-need.html', to: redirect('/all-the-webhooks-you-need')
    get '/2016/02/12/edit-your-yaml-files-like-a-boss.html', to: redirect('/edit-your-yaml-files-like-a-boss')
    get '/2016/02/11/xamarin-users-rejoice.html', to: redirect('/xamarin-users-rejoice')
    get '/2016/02/08/a-better-pricing-for-you.html', to: redirect('/a-better-pricing-for-you')
    get '/2016/02/04/let-s-move-to-the-new-stack.html', to: redirect('/lets-move-to-the-new-stack')
    get '/2016/01/20/here-comes-the-new-stack.html', to: redirect('/here-comes-the-new-stack')
    get '/2016/01/11/the-new-year-together.html', to: redirect('/the-new-year-together')
    get '/2015/11/23/finally-build-your-android-projects-on-bitrise.html', to: redirect('/finally-build-your-android-projects-on-bitrise')
    get '/2015/11/05/schedule-those-builds.html', to: redirect('/build-notification-emails-are-cooler-than-ever')
    get '/2015/11/05/schedule-those-builds.html', to: redirect('/schedule-those-builds')
    get '/2015/10/28/updated-build-logs-with-new-shiny-practical-features.html', to: redirect('/updated-build-logs-with-shiny-practical-features')
    get '/2015/10/19/booyah-our-command-line-interface-just-got-its-own-landing-page.html', to: redirect('/booyah-our-command-line-interface-just-got-its-own-landing-page')
    get '/2015/08/05/introducing-fastlane-on-bitrise.html', to: redirect('/introducing-fastlane-on-bitrise')
    get '/2015/06/24/a-tech-startup-in-london.html', to: redirect('/a-tech-startup-in-london')
    get '/2015/04/29/you-can-now-transfer-the-ownership-of-your-apps.html', to: redirect('/you-can-now-transfer-the-ownership-of-your-apps')
    get '/2015/04/28/announcing-status-images.html', to: redirect('/announcing-status-images')
    get '/2015/04/23/pull-request-support-for-github-repositories.html', to: redirect('/pull-request-support-for-github-repositories')
    get '/2015/01/29/the-new-workflow-system.html', to: redirect('/the-new-workflow-system')
    get '/2014/11/24/we-re-back-from-how-to-web.html', to: redirect('/were-back-from-how-to-web')
    get '/2014/10/29/bitrise-is-one-of-this-year-s-startup-spotlight-finalists.html', to: redirect('/bitrise-is-one-of-this-years-how-to-web-startup-spotlight-finalists')
    get '/2014/07/14/renaming.html', to: redirect('/renaming')

    get '(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/:slug' => 'posts#show', :as => :buttercms_post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/buttercms/authors_controller.rb
class Buttercms::AuthorsController < Buttercms::BaseController
	before_action :set_variables

	def show
		@author = ButterCMS::Author.find(params[:slug])
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size,
			author_slug: params[:slug]
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end
private
	def set_variables
		@categories = ButterCMS::Category.all
	end
end

app/controllers/buttercms/base_controller.rb
class Buttercms::BaseController < ActionController::Base
	# You can of course change this layout to your main application layout
	# to have your blog match the rest of your site.
	layout 'buttercms/default'
	include Response
	include ExceptionHandler

	def subscribe_user
		respond_to do |format|
			if !subscribe_params[:email].eql?("")
				begin
					encoded_authorization_token = "Basic " + Base64.strict_encode64("slapec:#{ENV['MAILCHIMP_API_TOKEN']}")

					query = "query=" + subscribe_params[:email]
					response = RestClient::Request.execute(
						method: :get,
						url: "#{ENV['MAILCHIMP_API_SERVER']}/search-members?#{query}",
						headers: {
							"Authorization": encoded_authorization_token
						}
					)
					response_body = JSON.parse(response.body)
					if response_body["exact_matches"]["total_items"] > 0
						format.json{ render json: {message: "already subscribed"}.to_json(), status: :ok }
					end

					response = RestClient::Request.execute(
						method: :post,
						url: "#{ENV['MAILCHIMP_API_SERVER']}/lists/#{ENV['MAILCHIMP_LIST_ID']}/members",
						headers: {
							"Authorization": encoded_authorization_token,
							"Content-Type": "application/json"
						},
						payload: {
							email_address: subscribe_params[:email],
							status: "subscribed"
						}.to_json()
					)
					format.json{ render json: {message: "ok"}.to_json(), status: :ok }
				rescue RestClient::ExceptionWithResponse
					format.json{ render json: {message: "invalid email"}.to_json(), status: :internal_server }
				end
			else
				format.json{ render json: {message: "empty email"}.to_json(), status: :bad_request }
			end
		end
	end

private

	def subscribe_params
		params.require(:base).permit(:email)
	end
end

app/controllers/buttercms/categories_controller.rb
class Buttercms::CategoriesController < Buttercms::BaseController
	before_action :set_variables

	def show
		@category = ButterCMS::Category.find(params[:slug])
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size,
			category_slug: params[:slug]
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end
private
	def set_variables
		@categories = ButterCMS::Category.all
	end
end

app/controllers/buttercms/feeds_controller.rb
class Buttercms::FeedsController < Buttercms::BaseController
  def sitemap
    feed = ButterCMS::Feed.find(:sitemap)

    render :xml => feed.data
  end

  def atom
    feed = ButterCMS::Feed.find(:atom)

    render :xml => feed.data
  end

  def rss
    feed = ButterCMS::Feed.find(:rss)

    render :xml => feed.data
  end
end

app/controllers/buttercms/posts_controller.rb
class Buttercms::PostsController < Buttercms::BaseController
	before_action :set_variables

	def index
		tag = ButterCMS::Tag.find("featured", include: 'recent_posts')
		@featured_post = tag.data.recent_posts.first unless tag.nil?

		@posts = ButterCMS::Post.all(:page => params[:page], :page_size => 6, include: 'recent_posts')

		@next_page = @posts.meta.next_page
		@previous_page = @posts.meta.previous_page
	end

	def show
		@post = ButterCMS::Post.find(params[:slug])

		meta_description_elements = parse_meta_description(@post.meta_description)
		@meta_description = meta_description_elements[:meta_description].strip!
		@authors = get_authors([@post.author.slug] + meta_description_elements[:authors])
		@next_post = @post.meta.next_post
		@previous_post = @post.meta.previous_post
	end

	def all_posts
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end

	def search_post
		@search_query = params[:query]
		render :search
	end

	def search
		page = post_params[:page] || 1
		page_size = post_params[:page] ? 6 : 100

		@posts = ButterCMS::Post.search(post_params[:query], {page: page, page_size: page_size})
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end

		rescue => ex
			if ex.class == ButterCMS::NotFound
				json_response(ex, :not_found)
			else
				json_response(ex, :internal_server)
			end
	end

private
	def post_params
		params.require(:post).permit(:query, :page, :page_size)
	end

	def set_variables
		@categories = ButterCMS::Category.all
		@tags = ButterCMS::Tag.all
	end

	def parse_meta_description(description)
		elements = description.split("*")
		meta_description = elements.first
		authors = elements[1..elements.length]
		return {
			meta_description: meta_description,
			authors: authors
		}
	end

	def get_authors(author_slugs)
		authors = []
		author_slugs.each do |author_slug|
			begin
				authors << ButterCMS::Author.find(author_slug)
			rescue => ex
				puts "[!] Exception: Author not found by slug (#{author_slug})! Exception: #{ex}, #{ex.inspect}"
			end
		end
		return authors
	end
end

app/controllers/buttercms/tags_controller.rb
class Buttercms::TagsController < Buttercms::BaseController
	before_action :set_variables

	def show
		@tag = ButterCMS::Tag.find(params[:slug])
	end

	def fetch_posts
		page = params[:page] || 1
		page_size = params[:page] ? 6 : 100

		@posts = ButterCMS::Post.all(
			page: page,
			page_size: page_size,
			tag_slug: params[:slug]
		)
		@number_of_posts = @posts.meta.count
		@next_page = @posts.meta.next_page

		respond_to do |format|
			format.json{ json_response({posts: @posts, total_count: @number_of_posts, next_page: @next_page}) }
		end
	rescue => ex
		if ex.class == ButterCMS::NotFound
			json_response(ex, :not_found)
		else
			json_response(ex, :internal_server)
		end
	end
private
	def set_variables
		@categories = ButterCMS::Category.all
	end
end

app/views/layouts/buttercms/default.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-53276411-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-53276411-1');
    </script>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TZK32GR');</script>
    <!-- End Google Tag Manager -->

    <!-- Freshpaint -->
    <script type="text/javascript">
      (function(f,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,c=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};c&&d(c,"state")&&(j=JSON.parse(decodeURIComponent(d(c,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",c),history.replaceState(j.desiredHash||"",f.title,k.pathname+k.search)))}catch(n){}var l,h;window.freshpaint=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
      0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="freshpaint";e.people=e.people||[];e.toString=function(b){var a="freshpaint";"freshpaint"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove people group page alias ready".split(" ");
      for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.4;b=f.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof FRESHPAINT_CUSTOM_LIB_URL?
      FRESHPAINT_CUSTOM_LIB_URL:"//perfalytics.com/static/js/freshpaint.js";d=f.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.freshpaint||[]);
      freshpaint.init("fb78fc32-b738-475e-b6e5-26f48c2ec5b1");
      freshpaint.page();

      (function () {
        var cookies = document.cookie.split('; ').reduce(function (result, chunk) {
          var parts = chunk.split('=')
          result[parts[0]] = parts[1]
          return result
        }, {})

        if (cookies['expiring_api_token'] && cookies['CSRF-TOKEN']) {
          var request = new XMLHttpRequest();
          request.onreadystatechange = function () {
            if (request.readyState === 4 && request.status === 200) {
              try {
                var resp = JSON.parse(request.responseText)

                if (resp.data.data_id) {
                  freshpaint.identify(resp.data.data_id)
                }
              } catch (ex) {
                console.log('Failed to fetch user')
              }
            }
          }
          var URL = 'https://api.bitrise.io/v0.1/me'
          request.open('GET', URL, true);
          request.setRequestHeader('Authorization', 'token ' + cookies['expiring_api_token'])
          request.setRequestHeader('X-CSRF-TOKEN', cookies['CSRF-TOKEN'])
          request.send(null);
        }
      })()
    </script>
    <!-- End Freshpaint -->

    <title><%= (content_for?(:html_title) ? "#{content_for(:html_title)} | Bitrise Blog" : "Bitrise Blog").html_safe %></title>

    <meta name="description" content="<%= content_for?(:meta_description) ? content_for(:meta_description) : "Articles about Continuous Integration & Delivery, automation, iOS code signing, DevOps, and awesome tech" %>">
    <meta name="viewport" content="viewport-fit=cover,width=device-width,minimum-scale=1,initial-scale=1">
    <link rel="canonical" href="https://blog.bitrise.io/<%= content_for(:canonical_url) %>" />
    <meta property="fb:app_id"        content="649161285439710" />
    <meta property="og:url"           content="https://blog.bitrise.io/<%= content_for(:canonical_url) %>" />
    <meta property="og:site_name"     content="Bitrise Blog" />
    <meta property="og:type"          content="article" />
    <meta property="og:title"         content="<%= content_for(:og_title) %>" />
    <meta property="og:description"   content="<%= content_for(:og_description) %>" />
    <meta property="og:image"         content="<%= content_for(:og_image) %>">
    <meta property="og:image:width"   content="<%= content_for(:og_image_width) %>">
    <meta property="og:image:height"  content="<%= content_for(:og_image_height) %>">

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@bitrise" />
    <meta name="twitter:creator" content="@bitrise" />
    <meta name="twitter:title" content="<%= content_for(:og_title) %>" />
    <meta name="twitter:description" content="<%= content_for(:og_description) %>" />
    <meta name="twitter:image" content="<%= content_for(:og_image) %>" />

    <link rel="alternate" type="application/atom+xml" title="Bitrise Blog - Atom" href="<%= buttercms_blog_atom_path %>">
    <link rel="alternate" type="application/rss+xml" title="Bitrise Blog - RSS" href="<%= buttercms_blog_rss_path %>">

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <link rel="shortcut mask-icon" type="image/x-icon" href="/favicon.svg">
    <link rel="apple-touch-icon" type="image/png" href="/apple-touch-icon.png">
    <link rel="apple-touch-icon" type="image/png" href="/apple-touch-icon-76x76.png" sizes="76x76">
    <link rel="apple-touch-icon" type="image/png" href="/apple-touch-icon-120x120.png" sizes="120x120">
    <link rel="apple-touch-icon" type="image/png" href="/apple-touch-icon-152x152.png" sizes="152x152">

    <!-- See https://buttercms.com/docs/#cssstyling -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//cloud.typography.com/7981312/721124/css/fonts.css' %>
    <link rel="stylesheet" media="screen" href="https://cloud.typography.com/7981312/721124/css/fonts.css">
    <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400,300,200,500,600,700,900">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/themes/prism-okaidia.min.css">
    <script src="https://unpkg.com/react@15/dist/react.min.js"></script>
    <script src="https://unpkg.com/react-dom@15/dist/react-dom.min.js"></script>
    <script src="https://use.typekit.net/etp1mcx.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>

</head>
<body>
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TZK32GR"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->

  <%= render :partial => 'navigation' %>
  <%= render :partial => 'categories' %>

  <div class="content">
    <%= yield %>
  </div>

  <%= render :partial => 'footer' %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', '<%= ENV['GA_MAIN_TOKEN'] %>', 'auto');
    ga('create', '<%= ENV['GA_TOKEN'] %>', 'auto', 'blogTracker');
    ga('send', 'pageview');
  </script>

  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/prism.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-yaml.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-json.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-bash.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-java.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-javascript.min.js"></script>
  <script>
  (function() {
    setTimeout( () => {
      Prism.highlightAll();
    }, 0)
  })(Prism);
  </script>
</body>
</html>